#! /bin/bash -x
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

yum update -y
yum groupinstall -y "Development Tools"
yum install -y kernel-devel epel-release
yum install -y dkms

/etc/init.d/tvncserver stop
systemctl isolate multi-user.target
killall Xvnc

chattr -i /etc/X11/xorg.conf

# Install vGPU Driver
# Install NVIDIA's 32-bit compatibility libraries?
# An incomplete installation of libglvnd was found. Do you want to install a full copy of libglvnd? This will overwrite any existing libglvnd libraries.
# Install x11 config
echo " ====> Downloading vGPU Driver"
wget -q https://swift-yyc.cloud.cybera.ca:8080/v1/AUTH_8c4974ed39a44c2fabd9d75895f6e28b/cybera_public/NVIDIA-GRID-Linux-KVM-410.92-410.91-412.16.zip
unzip NVIDIA-GRID-Linux-KVM-410.92-410.91-412.16.zip
chmod +x *.run

./NVIDIA-Linux-x86_64-410.92-grid.run --dkms -as -k $(uname -r) --install-libglvnd

# Cleanup NVIDIA
rm -f NVIDIA-GRID-Linux-KVM-410.92-410.91-412.16.zip
rm -f  410.92-410.91-412.16-grid-license-server-release-notes.pdf  
rm -f  410.92-410.91-412.16-grid-license-server-user-guide.pdf  
rm -f  410.92-410.91-412.16-grid-licensing-user-guide.pdf  
rm -f  410.92-410.91-412.16-grid-software-quick-start-guide.pdf  
rm -f  410.92-410.91-412.16-grid-vgpu-oem-qualification-test-plan.pdf  
rm -f  410.92-410.91-412.16-grid-vgpu-user-guide.pdf  
rm -f  410.92-410.91-412.16-kvm-reference-platform-partner-guidelines.pdf  
rm -f  412.16_grid_win10_server2016_64bit_international.exe  
rm -f  412.16_grid_win8_win7_server2012R2_server2008R2_64bit_international.exe  
rm -f  NVIDIA-Linux-x86_64-410.91-vgpu-kvm.run  
rm -f  NVIDIA-Linux-x86_64-410.92-grid.run

# Set up licensing
mkdir -p /etc/nvidia
cat << EOF | sudo tee /etc/nvidia/gridd.conf
ServerAddress=nvidia.dair-atir.canarie.ca
ServerPort=7070
FeatureType=2
EnableUI=False
LicenseInterval=1440
EOF

echo " ====> Downloading CUDA"
#10.1 not supported by latest vGPU driver (410.92)
#wget -q https://developer.nvidia.com/compute/cuda/10.1/Prod/local_installers/cuda_10.1.105_418.39_linux.run
wget -q https://developer.nvidia.com/compute/cuda/10.0/Prod/local_installers/cuda_10.0.130_410.48_linux
sudo chmod +x cuda_*

echo " ====> Installing CUDA"
sudo ./cuda* --silent --toolkit --samplespath=/usr/local/cuda/samples

cat << EOF | sudo tee /etc/ld.so.conf.d/ld-library.conf
# Add CUDA to LD
/usr/local/cuda/lib64
EOF

sudo ldconfig

nvidia-xconfig

# Clean up
chattr +i /etc/X11/xorg.conf

cd
sudo rm -rf cuda*
sudo rm -rf /root/NVIDIA*

sudo apt-get clean

#Ensure changes are written to disk
sync
